; Copyright (c) 2021 Fraunhofer AISEC. See the COPYRIGHT
; file at the top-level directory of this distribution.

; Licensed under the Apache License, Version 2.0 <LICENSE-APACHE or
; http://www.apache.org/licenses/LICENSE-2.0> or the MIT license
; <LICENSE-MIT or http://opensource.org/licenses/MIT>, at your
; option. This file may not be copied, modified, or distributed
; except according to those terms.

; This file shold be processed with cddl-gen (https://github.com/NordicSemiconductor/cddl-gen/tree/master) to create cbor encoding and decoding code 

aad_array = [
	oscore_version: uint,
	algorithms: [ alg_aead: int / tstr ],
	request_kid: bstr,
	request_piv: bstr,
	options: bstr,
]
