; Copyright (c) 2021 Fraunhofer AISEC. See the COPYRIGHT
; file at the top-level directory of this distribution.

; Licensed under the Apache License, Version 2.0 <LICENSE-APACHE or
; http://www.apache.org/licenses/LICENSE-2.0> or the MIT license
; <LICENSE-MIT or http://opensource.org/licenses/MIT>, at your
; option. This file may not be copied, modified, or distributed
; except according to those terms.

; This file should be processed with cddl-gen (https://github.com/NordicSemiconductor/cddl-gen/tree/master) to create cbor encoding and decoding code 

plaintext = (
	ID_CRED_x: map / bstr / int, SGN_or_MAC_x: bstr, ? AD_x: bstr)

;currently x5bag and x5u are not supported
map = {
	? kid: 4 =>  int, 
;	? x5bag: 32 => bstr,
	? x5chain: 33 => bstr, 
	? x5t: 34 => [int, bstr], 
;	? x5u: 35 => bstr, 
}

;map and id_cred_x_map are identical. 
;We just need different names to resolve inclusion conflicts
id_cred_x_map = {
	? kid: 4 =>  int, 
;	? x5bag: 32 => bstr,
	? x5chain: 33 => bstr, 
	? x5t: 34 => [int, bstr], 
;	? x5u: 35 => bstr, 
}




; Raw public keys are most optimally stored as COSE_Key objects and
;    identified with a 'kid' parameter:

;    *  ID_CRED_x = { 4 : kid_x }, where kid_x : bstr, for x = I or R.

; Public key certificates can be identified in different ways.  Header
;    parameters for identifying CBOR certificates and X.509 certificates
;    are defined in [I-D.mattsson-cose-cbor-cert-compress] and
;    [I-D.ietf-cose-x509], for example:

;    *  by a hash value with the 'c5t' or 'x5t' parameters;

;       -  ID_CRED_x = { 34 : COSE_CertHash }, for x = I or R,

;       -  ID_CRED_x = { TDB3 : COSE_CertHash }, for x = I or R,

;    *  by a URI with the 'c5u' or 'x5u' parameters;

;       -  ID_CRED_x = { 35 : uri }, for x = I or R,

;       -  ID_CRED_x = { TBD4 : uri }, for x = I or R,

;    *  ID_CRED_x MAY contain the actual credential used for
;       authentication, CRED_x.  For example, a DER encoded X.509
;       certificate chain can be transported in ID_CRED_x with COSE header
;       parameter x5chain, see Section 2 of [I-D.ietf-cose-x509].  This is
;       typically how certificates are transported within EDHOC.
